//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 05:24:29 PM EST 
//


package net.sigmaquest.supplychain.model;

import javax.xml.bind.annotation.XmlRegistry;
import com.thoughtworks.xstream.annotations.*;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sigmaquest.supplychain.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sigmaquest.supplychain.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValueInteger }
     * 
     */
    public ValueInteger createValueInteger() {
        return new ValueInteger();
    }

    /**
     * Create an instance of {@link TestRun }
     * 
     */
    public TestRun createTestRun() {
        return new TestRun();
    }

    /**
     * Create an instance of {@link ValueBoolean }
     * 
     */
    public ValueBoolean createValueBoolean() {
        return new ValueBoolean();
    }

    /**
     * Create an instance of {@link ValueTimestamp }
     * 
     */
    public ValueTimestamp createValueTimestamp() {
        return new ValueTimestamp();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ValueRecord }
     * 
     */
    public ValueRecord createValueRecord() {
        return new ValueRecord();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ValueString }
     * 
     */
    public ValueString createValueString() {
        return new ValueString();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Operator }
     * 
     */
    public Operator createOperator() {
        return new Operator();
    }

    /**
     * Create an instance of {@link ValueAttachment }
     * 
     */
    public ValueAttachment createValueAttachment() {
        return new ValueAttachment();
    }

    /**
     * Create an instance of {@link SetUp }
     * 
     */
    public SetUp createSetUp() {
        return new SetUp();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ValueDouble }
     * 
     */
    public ValueDouble createValueDouble() {
        return new ValueDouble();
    }

    /**
     * Create an instance of {@link ValueArray }
     * 
     */
    public ValueArray createValueArray() {
        return new ValueArray();
    }

    /**
     * Create an instance of {@link UnitReport }
     * 
     */
    public UnitReport createUnitReport() {
        return new UnitReport();
    }

}
