//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 05:24:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:unitreport-schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sigmaquest.supplychain.model;
