//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 05:24:29 PM EST 
//


package net.sigmaquest.supplychain.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import com.thoughtworks.xstream.annotations.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{urn:unitreport-schema}Property"/>
 *         &lt;element ref="{urn:unitreport-schema}SetUp"/>
 *         &lt;element ref="{urn:unitreport-schema}Result"/>
 *         &lt;element ref="{urn:unitreport-schema}TestRun"/>
 *         &lt;element ref="{urn:unitreport-schema}Error"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start-time" use="required" type="{urn:unitreport-schema}SigmaSureDateTime" />
 *       &lt;attribute name="end-time" type="{urn:unitreport-schema}SigmaSureDateTime" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="grade" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyOrSetUpOrResult"
})
@XmlRootElement(name = "TestRun")
@XStreamAlias("TestRun")
public class TestRun {

    @XmlElements({
        @XmlElement(name = "SetUp", type = SetUp.class),
        @XmlElement(name = "Result", type = Result.class),
        @XmlElement(name = "Property", type = Property.class),
        @XmlElement(name = "Error", type = Error.class),
        @XmlElement(name = "TestRun", type = TestRun.class)
    })
    @XStreamImplicit
    protected List<Object> propertyOrSetUpOrResult;
    @XmlAttribute(required = true)
    @XStreamAsAttribute
    protected String name;
    @XmlAttribute(name = "start-time", required = true)
    @XStreamAsAttribute
    @XStreamAlias("start-time") 
    protected String startTime;
    @XmlAttribute(name = "end-time")
    @XStreamAsAttribute
    @XStreamAlias("end-time") 
    protected String endTime;
    @XmlAttribute
    @XStreamAsAttribute
    protected String version;
    @XmlAttribute(required = true)
    @XStreamAsAttribute
    protected String grade;
    
    @XmlTransient
    protected Long testId;
    
    public Result getResult()
    {
    	if (propertyOrSetUpOrResult != null)
    	{
	    	for (Object o : propertyOrSetUpOrResult)
	    	{
	    		if (o instanceof Result)
	    			return (Result) o;
	    	}
    	}
    	else
    		System.out.println("TestRun.getResult(): propertyOrSetUpOrResult was null");
    	
    	return null;
    }

    public Property getProperty()
    {
    	if (propertyOrSetUpOrResult != null)
    	{
	    	for (Object o : propertyOrSetUpOrResult)
	    	{
	    		if (o instanceof Property)
	    			return (Property) o;
	    	}
    	}
    	return null;
    }
    
    public List<TestRun> getSubtests()
    {
    	List<TestRun> subtests = new ArrayList<TestRun>();
    	if (propertyOrSetUpOrResult != null)
    	{
	    	for (Object o : propertyOrSetUpOrResult)
	    	{
	    		if (o instanceof TestRun)
	    			subtests.add((TestRun)o);
	    	}
    	}
    	if (subtests.size() > 0)
    		return subtests;
    	else
    		return null;
    }
    
    
    
    public Long getTestId() {
		return testId;
	}

	public void setTestId(Long testId) {
		this.testId = testId;
	}

	/**
     * Gets the value of the propertyOrSetUpOrResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyOrSetUpOrResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyOrSetUpOrResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetUp }
     * {@link Result }
     * {@link Property }
     * {@link Error }
     * {@link TestRun }
     * 
     * 
     */
    public List<Object> getPropertyOrSetUpOrResult() {
        if (propertyOrSetUpOrResult == null) {
            propertyOrSetUpOrResult = new ArrayList<Object>();
        }
        return this.propertyOrSetUpOrResult;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrade(String value) {
        this.grade = value;
    }

}
