//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 05:24:29 PM EST 
//


package net.sigmaquest.supplychain.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.thoughtworks.xstream.annotations.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{urn:unitreport-schema}Station"/>
 *         &lt;element ref="{urn:unitreport-schema}Operator"/>
 *         &lt;element ref="{urn:unitreport-schema}Category"/>
 *         &lt;element ref="{urn:unitreport-schema}Property" minOccurs="0"/>
 *         &lt;element ref="{urn:unitreport-schema}TestRun"/>
 *       &lt;/all>
 *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" default="D" />
 *       &lt;attribute name="start-time" use="required" type="{urn:unitreport-schema}SigmaSureDateTime" />
 *       &lt;attribute name="end-time" type="{urn:unitreport-schema}SigmaSureDateTime" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="software-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attachments" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "UnitReport")
@XStreamAlias("UnitReport")
public class UnitReport {

    @XmlElement(name = "Station", required = true)
    @XStreamAlias("Station")
    protected Station station;
    @XmlElement(name = "Operator", required = true)
    @XStreamAlias("Operator")
    protected Operator operator;
    @XmlElement(name = "Category", required = true)
    @XStreamAlias("Category")
    protected Category category;
    @XmlElement(name = "Property")
    @XStreamAlias("Property")
    protected Property property;
    @XmlElement(name = "TestRun", required = true)
    @XStreamAlias("TestRun")
    protected TestRun testRun;
    @XmlAttribute
    @XStreamAsAttribute
    protected String mode;
    @XmlAttribute(name = "start-time", required = true)
    @XStreamAlias("start-time")  
    @XStreamAsAttribute
    protected String startTime;
    @XmlAttribute(name = "end-time")
    @XStreamAlias("end-time")  
    @XStreamAsAttribute
    protected String endTime;
    @XmlAttribute
    @XStreamAsAttribute
    protected String version;
    @XmlAttribute
    @XStreamAsAttribute
    protected Long quantity;
    @XmlAttribute(name = "software-version")
    @XStreamAsAttribute
    @XStreamAlias("software-version")
    protected String softwareVersion;
    @XmlAttribute
    @XStreamAsAttribute
    protected Boolean attachments;
    
    protected String filename;

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStation(Station value) {
        this.station = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link Operator }
     *     
     */
    public Operator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operator }
     *     
     */
    public void setOperator(Operator value) {
        this.operator = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link Property }
     *     
     */
    public Property getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link Property }
     *     
     */
    public void setProperty(Property value) {
        this.property = value;
    }

    /**
     * Gets the value of the testRun property.
     * 
     * @return
     *     possible object is
     *     {@link TestRun }
     *     
     */
    public TestRun getTestRun() {
        return testRun;
    }

    /**
     * Sets the value of the testRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestRun }
     *     
     */
    public void setTestRun(TestRun value) {
        this.testRun = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        if (mode == null) {
            return "P";
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantity(Long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAttachments(Boolean value) {
        this.attachments = value;
    }

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Product getProduct()
	{
		for (Object o : this.getCategory().getPropertyOrProductOrCategory())
		{
			if (o instanceof Product)
				return (Product) o;
		}
		return null;
	}
}
