//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 05:24:29 PM EST 
//


package net.sigmaquest.supplychain.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import com.thoughtworks.xstream.annotations.*;
import com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usl" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="lsl" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="udil" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ldil" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="uom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="grade" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "ValueDouble")
@XStreamAlias("ValueDouble")
@XStreamConverter(value=ToAttributedValueConverter.class, strings={"value"})
public class ValueDouble implements ValueBase {

    @XmlValue
    protected double value;
    @XmlAttribute
    @XStreamAsAttribute
    protected String name;
    @XmlAttribute
    @XStreamAsAttribute
    protected Double usl;
    @XmlAttribute
    @XStreamAsAttribute
    protected Double lsl;
    @XmlAttribute
    @XStreamAsAttribute
    protected Double udil;
    @XmlAttribute
    @XStreamAsAttribute
    protected Double ldil;
    @XmlAttribute
    @XStreamAsAttribute
    protected String uom;
    @XmlAttribute
    @XStreamAsAttribute
    protected String grade;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the usl property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUsl() {
        return usl;
    }

    /**
     * Sets the value of the usl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUsl(Double value) {
        this.usl = value;
    }

    /**
     * Gets the value of the lsl property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLsl() {
        return lsl;
    }

    /**
     * Sets the value of the lsl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLsl(Double value) {
        this.lsl = value;
    }

    /**
     * Gets the value of the udil property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUdil() {
        return udil;
    }

    /**
     * Sets the value of the udil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUdil(Double value) {
        this.udil = value;
    }

    /**
     * Gets the value of the ldil property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLdil() {
        return ldil;
    }

    /**
     * Sets the value of the ldil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLdil(Double value) {
        this.ldil = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUom(String value) {
        this.uom = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrade(String value) {
        this.grade = value;
    }
    
    public String getNameString() {
        return name;
    }
	@Override
	public String getUnitString() {
		return this.getUom();
	}

	@Override
	public String getLslString() {
		if (lsl != null)
			return this.lsl.toString();
		else
			return null;
	}

	@Override
	public String getUslString() {
		if (usl != null)
			return this.usl.toString();
		else
			return null;
	}

	@Override
	public String getValueString() {
		return String.valueOf(this.value);
	}
	
	@Override
	public String getGradeString() {
		return grade;
	}

}
